version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: calendario_festivos
      POSTGRES_USER: festivos_user
      POSTGRES_PASSWORD: festivos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: dockerapicalendario
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/calendario_festivos
      SPRING_DATASOURCE_USERNAME: festivos_user
      SPRING_DATASOURCE_PASSWORD: festivos_pass

volumes:
  postgres_data: